src/apps/cars/urls.py
from django.urls import path

from src.apps.post import views
from src.apps.cars.views import car_filter
from django.views.generic import TemplateView ,  RedirectView 

from django.urls import path , include

urlpatterns = [
    path('', views.car_filter, name='car_filter'),

    
    path('cars_list/', views.CarListView.car_list, name='cars'),
    path('car_list/', views.car_filter, name='car_filter'),


    path('add_car/', views.add_car, name='add_car'),
    path('favorites_list/' , views.favorites_list , name='favorites_list'),

    path('cars/<int:car_id>/', views.detail_page, name='detail_page'),

    path('update_car/<int:car_id>/', views.update_car, name='update_car'),

    path('cars/delete/<int:car_id>/', views.delete_car, name='delete_car'),

    path('car_filter/', views.car_filter, name='car_filter'),
    path('car_filter/<int:pk>/', views.filtered_cars, name='filtered_cars'),

    path('favorites_list/add/<int:pk>' , views.add_to_favorites_list , name = 'add_to_favorites'),
    path('favorites_list/remove/<int:pk>' , views.remove_to_favorites_list , name = 'remove_to_favorites') ,


    path("get_make_models/<int:pk>/", views.get_car_make_models ),

]

src/config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('accounts/', include('allauth.urls')),

    path('admin/', admin.site.urls),
    
    path('user/', include("src.apps.user.urls")),
    path('cars/', include("src.apps.cars.urls")),
    path('spare_part/', include("src.apps.spare_part.urls")),
    path('' , include("src.apps.post.urls")) ,  
  
]



from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/cars/models.py
from src.apps.user.models import User
from src.apps.cars.choices import *

class CarMake(models.Model):
    name = models.CharField(max_length=100, verbose_name='Марка')
    
    def __str__(self):
        return self.name

class CarModel(models.Model):
    cars = models.ForeignKey(CarMake, on_delete=models.CASCADE, related_name="models",null=True)
    name = models.CharField(max_length=100, verbose_name='Модель')
    
    def __str__(self):
        return self.name
    

class Special_notes(models.Model):
    name = models.CharField(max_length=150, verbose_name='Особенные приметы' , null=True, blank=True)
    
    
    def __str__(self):
        return f"{self.name}"

class Car(models.Model):
    mark = models.ForeignKey(CarMake, on_delete=models.CASCADE, verbose_name='Марка')
    model = models.ForeignKey(CarModel, on_delete=models.CASCADE, verbose_name='Модель')
    owner = models.ForeignKey(User, on_delete=models.CASCADE , related_name= "Владелец")    
    description = models.CharField("Описание" , max_length=500 , null=True)
    year = models.PositiveIntegerField(verbose_name='Год выпуска')
    
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    body_type = models.CharField("Тип кузова", max_length=13, choices=BodyType.choices)
    engine = models.CharField("топливо", max_length=13, choices=Engine.choices)
    
    views_count = models.PositiveIntegerField("Количество просмотров", default=0)
    mileage = models.PositiveIntegerField(verbose_name='Пробег', default=0, help_text="Км")
   
    drive = models.CharField("привод", max_length=20, choices=DriveType.choices)
    gearbox = models.CharField("коробка передач", max_length=15, choices=GearboxType.choices)
    engine_capacity = models.DecimalField(max_digits=4, decimal_places=1, verbose_name='Объем двигателя л')
    ruletype = models.CharField("Тип руля", max_length=5, choices=RuleType.choices, default=RuleType.LEFT)
    color = models.CharField("цвет автомобиля", max_length=15, choices=Color.choices)

    location = models.URLField("Адрес" ,max_length=200 , null=True , blank=True)

    condition = models.CharField("состояние", max_length=21, choices=ConditionType.choices)
    customs_cleared = models.CharField("расстаможен", max_length=25, choices=Customs_cleared.choices)
    vin_code = models.CharField("наличие вин кода",max_length=5,choices=VINcode.choices, default= False ,blank=True,)
    currency = models.CharField("валюта" , max_length=11 , choices=Currency.choices , default= Currency.USD)
    special_notes = models.ManyToManyField(Special_notes  , blank=True)
    additional_note = models.CharField("Дополнительние приметы", max_length=255, null=True, blank=True)


    def __str__(self):
        return f"{self.mark} {self.model} ({self.year})"


class CarPhoto(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE, related_name='photos', null=True)
    image = models.ImageField("Изображение",
          upload_to="cars/images/", 
          null=True,blank=True
          )
    is_main = models.BooleanField("Главное фото", default=False)
    
    
    class Meta:
        verbose_name_plural="Car image" 


    def __str__(self):
        return "Photos"

src/apps/cars/forms.py
from django import forms
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Div, Row, Column
from django.forms.models import inlineformset_factory

from datetime import datetime
from django import forms
now_year = datetime.now().year

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput)
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result



class CarForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
                Fieldset(
                    '',
                    Row(
                        Column('mark', css_class='col-md-6 my-field-class'),  
                        Column('model', css_class='col-md-6 my-field-class'),  
                    ),
                    Row(
                        Column('price', css_class='col-md-6 my-field-class'),  
                        Column('currency', css_class='col-md-6 my-field-class'),  
                    ),
                    Row(
                        Column('mileage' , css_class='col-md-4 my-field-class' ) ,
                        Column('year' , css_class='col-md-4 my-field-class'),
                        Column('location' ,css_class='col-md-4 my-field-class' )
                    ),
                    Row(
                    Column('description', css_class='col-md-6 my-field-class'),
                    Column('vin_code',css_class='col-md-6'),
                    )   
                     
                ),

            Fieldset(
                '',
                Row(
                    Column('body_type', css_class='form-group col-md-4 mb-0'),
                    Column('engine', css_class='form-group col-md-4 mb-0'),
                    Column('engine_capacity', css_class='form-group col-md-4 mb-0'),
                    css_class='form-row'
                ),
                Row(
                    Column('drive', css_class='form-group col-md-4 mb-0'),
                    Column('gearbox', css_class='form-group col-md-4 mb-0'),
                    Column('ruletype', css_class='form-group col-md-4 mb-0'),
                    css_class='form-row'
                ),
                Row(
                    Column('color', css_class='form-group col-md-4 mb-0'),
                    Column('condition', css_class='form-group col-md-4 mb-0'),
                    Column('customs_cleared', css_class='form-group col-md-4 mb-0'),
                    css_class='form-row'
                ),

                 Fieldset(
                'Фотографии',
                Row(
                    Column(
                        'photos',
                        css_class='col-md-12',
                    ),
                ),

            ),
                Fieldset(
                    'Особенные приметы',
                    Row(
                        Column(
                            'special_notes',
                            css_class='col-md-12',
                        ),
                    ),
                    Row(
                        Column('additional_note', css_class='col-md-6 my-field-class'),
                    ),
                ),
            ) ,
                Div(
                Submit('submit', 'Сохранить'))
            )
        
            
    
    mark = forms.ModelChoiceField(queryset=CarMake.objects.all(), label='Марка' )
    model = forms.ModelChoiceField(queryset=CarModel.objects.all(), label='Модель')
    currency = forms.ChoiceField(choices=Currency.choices, label='Валюта')
    price = forms.DecimalField(max_digits=10, decimal_places=2, label='Цена')  
    description = forms.CharField(max_length=500 , label="описание")
    mileage = forms.IntegerField(label='Пробег', min_value=0, required=True)
    year = forms.IntegerField(max_value=now_year, label='Год выпуска')
    body_type = forms.ChoiceField(choices=BodyType.choices, label='Тип кузова')
    engine = forms.ChoiceField(choices=Engine.choices, label='Топливо')
    engine_capacity = forms.DecimalField(max_digits=4, decimal_places=1, label='Объем двигателя (л)')
    drive = forms.ChoiceField(choices=DriveType.choices, label='Привод')
    gearbox = forms.ChoiceField(choices=GearboxType.choices, label='Коробка передач')
    ruletype = forms.ChoiceField(choices=RuleType.choices, label='Тип руля')
    color = forms.ChoiceField(choices=Color.choices, label='Цвет автомобиля')
    condition = forms.ChoiceField(choices=ConditionType.choices, label='Состояние')
    customs_cleared = forms.ChoiceField(choices=Customs_cleared.choices, label='Расстаможен')
    vin_code = forms.ChoiceField(choices=VINcode.choices, label='Наличие VIN кода')
    location = forms.CharField(required=False, max_length=300 , label="Адрес")
    

    special_notes = forms.ModelMultipleChoiceField(
        queryset=Special_notes.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
        label='Особенные приметы'
    )

    photos = MultipleFileField()
    
    class Meta:
        model = Car
        
        fields = ['mark', 'model', 'year', 'mileage', 'description', 'body_type', 'ruletype', 
              'drive', 'gearbox', 'engine', 'engine_capacity', 'color', 'condition', 'customs_cleared', 
              'vin_code', 'currency', 'price', 'special_notes', 'photos', 'additional_note', 'location'
              ]

class CarPhotoForm(forms.ModelForm):             
    class Meta:
        model = CarPhoto
        fields = ['image',]

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'avatar', 'mobile', 'favorites_list', 'currency']
        labels = {
            'email': 'Email',
            'avatar': 'Аватарка',
            'mobile': 'Номер телефона',
            'favorites_list': 'Избранные автомобили',
            'currency': 'Валюта'
        }   

class CarFilterForm(forms.Form):
    makes = CarMake.objects.all().values_list('name', 'name').distinct()
    models = CarModel.objects.all().values_list('name', 'name').distinct()
    years = Car.objects.values_list('year', 'year').distinct()
    # Другие поля формы

    make = forms.ChoiceField(choices=[('', 'Все')] + list(makes), required=False)
    model = forms.ChoiceField(choices=[('', 'Все')] + list(models), required=False)
    year = forms.ChoiceField(choices=[('', 'Все')] + list(years), required=False)
    min_price = forms.DecimalField(min_value=0, required=False, widget=forms.NumberInput(attrs={'placeholder': 'Минимальная цена'}))
    max_price = forms.DecimalField(min_value=0, required=False, widget=forms.NumberInput(attrs={'placeholder': 'Максимальная цена'}))
    # Другие поля формы

src/apps/cars/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponseBadRequest

from src.apps.cars.filter import CarFilter
from .models import Car, CarModel, CarMake
from .forms import *
from django.core.paginator import Paginator, Page

from django.views.generic import View , ListView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

from django.http.response import HttpResponse
# Create your views here.

class CarListView(ListView):
    model = Car
    template_name = 'car_list.html'  # Шаблон для отображения списка элементов
    context_object_name = 'list'  # Имя переменной контекста для списка элементов
    paginate_by = 5

    def car_list(request):
        cars = Car.objects.all()
        cars_per_page = 3
        paginator = Paginator(cars, cars_per_page)
        page_number = request.GET.get('page')
        page = paginator.get_page(page_number)

        return render(request, 'cars_list.html', {'page': page})

@login_required
def add_car(request):
    if request.method == 'POST':
        form = CarForm(request.POST, request.FILES)
        print(form.is_valid())
        # print(special_notes_form.is_valid())
        if form.is_valid():

            car = form.save(commit=False)
            car.owner = request.user
            car.save()
            form.save_m2m()

            photos = request.FILES.getlist('photos')
            
            for photo in photos:
                CarPhoto.objects.create(
                    image=photo,
                    car=car
                )
            return redirect('cars')
    else:
        form = CarForm()
        photo_form = CarPhotoForm()
    return render(request, 'add_car.html',  {'form': form})

@login_required
def delete_car(request, car_id):
    car = get_object_or_404(Car, pk=car_id)
    car.delete()
    return redirect('profile', user_id=request.user.id) 

@login_required
def favorites_list(request):
    user = request.user
    favorites = user.favorites_list.all()
    context = {'favorites': favorites}
    return render(request, 'favorites_list.html', context)


@login_required
def detail_page(request, car_id):
    car = get_object_or_404(Car, id=car_id)
    print(car.views_count)
    car.views_count += 1 
    print(car.views_count)
    car.save()  

    car_photos = car.photos.all()
    context = {
        'car': car,
        'car_photos': car_photos,
    }
    return render(request, 'detail_page.html', context)



@login_required
def add_to_favorites_list(request , pk):
    user = request.user
    car = get_object_or_404(Car , id=pk)
    if car in user.favorites_list.all() :
        return HttpResponse("Fail")
    else:
        user.favorites_list.add(car)
    return redirect ("cars")

@login_required
def remove_to_favorites_list(request,pk):
    user = request.user
    car = get_object_or_404(Car , id=pk)
    if car in user.favorites_list.all() :
        user.favorites_list.remove(car)
        
    else:
        return HttpResponse("Fail")
    return redirect ("favorites_list")
    
# второй вариант 


def car_filter(request):
    # Создайте объект фильтрации на основе GET-параметров
    filter = CarFilter(request.GET, queryset=Car.objects.all())
    
    # Если форма отправлена, примените фильтр к запросу
    if filter.is_valid():
        cars = filter.qs
    else:
        cars = Car.objects.all()  # Если форма не валидна, покажите все машины
        
    return render(request, 'car_filter.html', {'filter': filter, 'cars': cars})
@login_required
def filtered_cars(request, pk=None):
    # Получите объект машины по ее Primary Key (pk)
    if pk:
        car = get_object_or_404(Car, pk=pk)
    else:
        car = None

    # Создайте объект фильтрации на основе GET-параметров
    filter = CarFilter(request.GET, queryset=Car.objects.all())
    
    # Если форма отправлена, примените фильтр к запросу
    if filter.is_valid():
        cars = filter.qs
    else:
        cars = Car.objects.all()

    return render(request, 'car_filter.html', {'filter': car, 'cars': cars})

@login_required
def update_car(request, car_id):
    car_instance = get_object_or_404(Car, id=car_id)

    if request.method == 'POST':
        form = CarForm(request.POST, instance=car_instance)
        if form.is_valid():
            form.save()
            return redirect('detail_page', car_id=car_id)  # Redirect to car detail page
    else:
        form = CarForm(instance=car_instance)

    return render(request, 'car_update_form.html', {'form': form})



from django.http import JsonResponse


@login_required
def get_car_make_models(request, pk): 
    make = CarMake.objects.get(id=pk)
    models = CarModel.objects.filter(cars=make).values_list("id", "name")
    data = {
        "items":list(models)
    }
    print(models)
    return JsonResponse(data=data)
    

src/apps/cars/templates/add_car.html
{% extends 'base.html' %} 
{% load static %}
{% block content %} 

{% load crispy_forms_tags %}
<div class="page-wrapper">
    <div class="page-body">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% crispy form %}
            <!-- <input type="file" name="photos" accept="image/*" multiple> -->
            
            
        </form>
    </div>        
</div>
{% endblock %}


{% block js %}
    <script>
        let make = document.getElementById("id_mark");
        let model = document.getElementById("id_model");

        make.addEventListener('change', function () {
        let make_id = this.value;
        
        // Создайте объект FormData для отправки данных на сервер

        // Отправьте POST-запрос на сервер с использованием fetch
        fetch('/cars/get_make_models/'+make_id+'/', {
            method: 'GET',
        })
        .then(response => response.json())
        .then(data => {

            // Обновите второй select с полученными данными
            model.innerHTML = '';
            data.items.forEach(function(item) {
                var id = item[0];
                var text = item[1];

                var option = document.createElement('option');
                option.value = id;
                option.text = text;

                model.appendChild(option);
            });
        })
        .catch(error => console.error('Ошибка при выполнении AJAX-запроса:', error));
    });


    </script>

{% endblock %}

src/apps/cars/templates/car_update_form.html
{% extends 'base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% crispy form %}
    
</form>
{% endblock %}

src/apps/cars/templates/detail_page.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

{% if car.photos.first %}
        
<div class="page-wrapper">
  
<div class="page-body">
  <div class="container-xl">
    <div class="row g-2 g-md-3">
      <div class="col-lg-6">
        <div class="row g-2 g-md-3">
          {% for photo in car_photos %}
          <div class="col-6 col-md-3">
            <a data-fslightbox="gallery" href="{{ photo.image.url }}">
              <div class="img-responsive img-responsive-1x1 rounded-3 border" style="background-image: url('{{ photo.image.url }}')"></div>
            </a>
          </div>
          {% if forloop.counter|divisibleby:4 %} <!-- Добавляем условие для каждой четвертой фотографии -->
            <div class="w-100 d-md-none"></div> <!-- Добавляем разделительный элемент для перехода на новый ряд только на маленьких экранах -->
          {% endif %}
          {% endfor %} 
        </div>
      </div>
    </div>
  </div>
</div>
      {% endif %}
  
      <!-- Page body -->
  <div class="page-body">
    <div class="container-xl">
      <div class="row row-cards">
        <div class="col-10">
          <div class="card">
            <div class="table-responsive">
              <table
class="table table-vcenter card-table table-striped">
                <thead>
                  <tr>
                    <th>Марка</th>
                    <th>Модель</th>
                    <th>Обьем</th>
                    <th>Год</th>
                    <th>Цена</th>
                    <th>Валюта</th>
                    <th class="w-1"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td >{{ car.mark.name }}</td>
                    <td class="text-muted" >{{ car.model.name }}</td>
                    <td class="text-muted" >{{ car.engine_capacity }} л</td>
                    <td class="text-muted" >{{ car.year }}</td>
                    <td class="text" >{{ car.price }}</td>
                    <td class="text-muted" >{{ car.currency }}</td>
                    
                  </tr>

                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col-10">
          <div class="card">
            <div class="table-responsive">
              <table
 class="table table-vcenter card-table table-striped">
                <thead>
                  <tr>
                    <th>Состояние</th>
                    <th>Цвет</th>
                    <th>Расстаможка</th>
                    <th>VIN код</th>
                    <th>Руль</th>
                    <th>Просмотры</th>
                    <th class="w-1"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td >{{ car.get_condition_display }}</td>
                    <td class="text-muted" >{{ car.get_color_display }}</td>
                    <td class="text-muted" >{{ car.get_customs_cleared_display }}</td>
                    <td class="text-muted" >{{ car.get_vin_code_display }}</td>
                    <td class="text-muted" >{{ car.get_ruletype_display }}</td>
                    <td class="text-muted" >{{ car.views_count }}</td>    
                  </tr>

                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col-10">
          <div class="card">
            <div class="table-responsive">
              <table
                      class="table table-vcenter card-table table-striped">
                <thead>
                  <tr>
                    <th>Кпп</th>
                    <th>Двигатель</th>
                    <th>Пробег</th>
                    <th>Кузов</th>
                    <th>Привод</th>
                    <th>Номер</th>
                    <th>Месторасположение</th>
                    <th class="w-1"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td >{{ car.get_gearbox_display }}</td>
                    <td class="text-muted" >{{ car.get_engine_display }}</td>
                    <td class="text-muted" >{{ car.mileage }} км</td>
                    <td class="text-muted" >{{ car.get_body_type_display }}</td>
                    <td class="text-muted" >{{ car.get_drive_display }}</td> 
                    <td class="text-muted" ><a href="tel:+{{ car.owner.mobile }}">+ {{ car.owner.mobile }}</a> </td>
                    {% if "https" in car.location %}
                        <td class="text-muted">
                            <a href="{{ car.location }}" target="_blank">
                                <span>Местонахождение</span>
                            </a>
                        </td>
                    {% else %}
                        <td class="text-muted">{{ car.location }}</td>
                    {% endif %}
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col-10">
          <div class="card">
            <div class="table-responsive">
              <table
                      class="table table-vcenter card-table table-striped">
                <thead>
                  <tr>
                    <th>Описание</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td >{{ car.description }}</td>
                    
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col-10">
          <div class="card">
            <div class="table-responsive">
              <table
                      class="table table-vcenter card-table table-striped">
                <thead>
                  <tr>
                    <th>Внешние особенности</th>
                  </tr>
                </thead>
                {% for note in car.special_notes.all %}
                <tbody>
                    <td>{{ note.name }}</td>
                  {% empty %}
                      <td>Не указано</td>
                </tbody>
                {% endfor %}
              </table>
            </div>
          </div>
          <div class="card-footer bg-transparent mt-auto">
            <div class="btn-list justify-content-end">
              {% if request.user == car.owner %}
                  <a href="{% url 'delete_car' car_id=car.id %}" class="btn btn-outline-danger">
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash-filled" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
          <path d="M20 6a1 1 0 0 1 .117 1.993l-.117 .007h-.081l-.919 11a3 3 0 0 1 -2.824 2.995l-.176 .005h-8c-1.598 0 -2.904 -1.249 -2.992 -2.75l-.005 -.167l-.923 -11.083h-.08a1 1 0 0 1 -.117 -1.993l.117 -.007h16z" stroke-width="0" fill="currentColor"></path>
          <path d="M14 2a2 2 0 0 1 2 2a1 1 0 0 1 -1.993 .117l-.007 -.117h-4l-.007 .117a1 1 0 0 1 -1.993 -.117a2 2 0 0 1 1.85 -1.995l.15 -.005h4z" stroke-width="0" fill="currentColor"></path>
          </svg>
                      Удалить
                  </a>
                  <a href="{% url 'update_car' car_id=car.id %}" class="btn btn-primary">
                    Изменить
                  </a>
              {% endif %}
            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}